services:
  postgres:
    image: ghcr.io/postgresml/postgresml:2.10.0
    platform: linux/amd64
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basic_mcp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_ml:/var/lib/postgresql/data

volumes:
  postgres_data_ml: